baseURL = 'https://pawel.staniec.eu/'
languageCode = 'en-us'
title = 'Pawe≈Ç Staniec'

[params]
description = 'A custom Hugo site built from scratch'
author = 'Your Name'

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 20
  [[menu.main]]
    name = 'Posts'
    url = '/posts/'
    weight = 30

  [[menu.secondary]]
    name = 'GitHub'
    url = 'https://github.com/pawelst'
    weight = 10
  [[menu.secondary]]
    name = 'LinkedIn'
    url = 'https://linkedin.com/in/pawelstaniec'
    weight = 20
    